function X = ctrl_state2state(ctrl_state);
    X = [ctrl_state(3); ctrl_state(6);...
              ctrl_state(7); ctrl_state(10);...
              ctrl_state(8); ctrl_state(11);...
              ctrl_state(9); ctrl_state(12);...
              ctrl_state(13:16)];
end